### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Procodx**
made some changes in the readme file to make it look more official and technical

### CODE REVIEW

**Comment by n1lby73** [comment]
nice work here, but can you kindly tweak it more a bit as python flask was used for both the backend api and email verification

**Comment by Procodx** [comment]
Ok

**Comment by n1lby73** [comment]
> Ok

would be awaiting the pr, thanks once again for the contribution

**Comment by Procodx** [comment]
What pr??

**Comment by n1lby73** [comment]
> What pr??

Pull Request

**Review by n1lby73 — APPROVED** [review]
Thanks for your contribution

**Pull request merged**
